# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Mon Nov 24 05:42:33 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout.addWidget(self.mdiArea)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuMedical = QtGui.QMenu(self.menubar)
        self.menuMedical.setObjectName("menuMedical")
        self.menuPendaftaran = QtGui.QMenu(self.menubar)
        self.menuPendaftaran.setObjectName("menuPendaftaran")
        self.menuPencarian = QtGui.QMenu(self.menubar)
        self.menuPencarian.setObjectName("menuPencarian")
        self.menuBantuan = QtGui.QMenu(self.menubar)
        self.menuBantuan.setObjectName("menuBantuan")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPasien = QtGui.QAction(MainWindow)
        self.actionPasien.setObjectName("actionPasien")
        self.actionJadwal_Kedatangan = QtGui.QAction(MainWindow)
        self.actionJadwal_Kedatangan.setObjectName("actionJadwal_Kedatangan")
        self.actionPasien_2 = QtGui.QAction(MainWindow)
        self.actionPasien_2.setObjectName("actionPasien_2")
        self.actionDokter = QtGui.QAction(MainWindow)
        self.actionDokter.setObjectName("actionDokter")
        self.actionJadwal_Kedatangan_2 = QtGui.QAction(MainWindow)
        self.actionJadwal_Kedatangan_2.setObjectName("actionJadwal_Kedatangan_2")
        self.actionPesan = QtGui.QAction(MainWindow)
        self.actionPesan.setObjectName("actionPesan")
        self.actionAktifitas = QtGui.QAction(MainWindow)
        self.actionAktifitas.setObjectName("actionAktifitas")
        self.actionDashboard = QtGui.QAction(MainWindow)
        self.actionDashboard.setObjectName("actionDashboard")
        self.actionSetting = QtGui.QAction(MainWindow)
        self.actionSetting.setCheckable(False)
        self.actionSetting.setObjectName("actionSetting")
        self.actionTentang = QtGui.QAction(MainWindow)
        self.actionTentang.setObjectName("actionTentang")
        self.actionFAQ = QtGui.QAction(MainWindow)
        self.actionFAQ.setObjectName("actionFAQ")
        self.actionTentang_2 = QtGui.QAction(MainWindow)
        self.actionTentang_2.setObjectName("actionTentang_2")
        self.menuMedical.addAction(self.actionDashboard)
        self.menuMedical.addSeparator()
        self.menuMedical.addAction(self.actionSetting)
        self.menuPendaftaran.addAction(self.actionPasien)
        self.menuPendaftaran.addSeparator()
        self.menuPendaftaran.addAction(self.actionJadwal_Kedatangan)
        self.menuPencarian.addAction(self.actionPasien_2)
        self.menuPencarian.addSeparator()
        self.menuPencarian.addAction(self.actionJadwal_Kedatangan_2)
        self.menuPencarian.addSeparator()
        self.menuPencarian.addAction(self.actionPesan)
        self.menuPencarian.addAction(self.actionAktifitas)
        self.menuBantuan.addAction(self.actionTentang)
        self.menuBantuan.addAction(self.actionFAQ)
        self.menuBantuan.addSeparator()
        self.menuBantuan.addAction(self.actionTentang_2)
        self.menubar.addAction(self.menuMedical.menuAction())
        self.menubar.addAction(self.menuPendaftaran.menuAction())
        self.menubar.addAction(self.menuPencarian.menuAction())
        self.menubar.addAction(self.menuBantuan.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Medcal", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMedical.setTitle(QtGui.QApplication.translate("MainWindow", "Menu Utama", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPendaftaran.setTitle(QtGui.QApplication.translate("MainWindow", "Pendaftaran", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPencarian.setTitle(QtGui.QApplication.translate("MainWindow", "Pencarian", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBantuan.setTitle(QtGui.QApplication.translate("MainWindow", "Bantuan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPasien.setText(QtGui.QApplication.translate("MainWindow", "Pasien Baru", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJadwal_Kedatangan.setText(QtGui.QApplication.translate("MainWindow", "Kedatangan && Janji", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPasien_2.setText(QtGui.QApplication.translate("MainWindow", "Pasien", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDokter.setText(QtGui.QApplication.translate("MainWindow", "Dokter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJadwal_Kedatangan_2.setText(QtGui.QApplication.translate("MainWindow", "Jadwal Kedatangan && Janji", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPesan.setText(QtGui.QApplication.translate("MainWindow", "Pesan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAktifitas.setText(QtGui.QApplication.translate("MainWindow", "Aktivitas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDashboard.setText(QtGui.QApplication.translate("MainWindow", "Dashboard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetting.setText(QtGui.QApplication.translate("MainWindow", "Pengaturan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTentang.setText(QtGui.QApplication.translate("MainWindow", "Cara Penggunaan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFAQ.setText(QtGui.QApplication.translate("MainWindow", "FAQ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTentang_2.setText(QtGui.QApplication.translate("MainWindow", "Tentang", None, QtGui.QApplication.UnicodeUTF8))

